-- ================================================================
-- RAJASTHAN STATIONS
-- ================================================================
INSERT INTO stations (station_name, city) VALUES

-- Already in DB (skip these):
-- Jaipur Junction, Jodhpur Junction, Udaipur City,
-- Ajmer Junction, Kota Junction

-- Additional Rajasthan Stations
('Bikaner Junction', 'Bikaner'),
('Alwar Junction', 'Alwar'),
('Bharatpur Junction', 'Bharatpur'),
('Sawai Madhopur Junction', 'Sawai Madhopur'),
('Gangapur City Junction', 'Gangapur City'),
('Sikar Junction', 'Sikar'),
('Churu Junction', 'Churu'),
('Sri Ganganagar Junction', 'Sri Ganganagar'),
('Hanumangarh Junction', 'Hanumangarh'),
('Sujangarh Junction', 'Sujangarh'),
('Nagaur Junction', 'Nagaur'),
('Pali Marwar Junction', 'Pali'),
('Barmer Junction', 'Barmer'),
('Jaisalmer Junction', 'Jaisalmer'),
('Bhilwara Junction', 'Bhilwara'),
('Chittorgarh Junction', 'Chittorgarh'),
('Dungarpur Road', 'Dungarpur'),
('Banswara Road', 'Banswara'),
('Bundi Junction', 'Bundi'),
('Tonk Junction', 'Tonk'),
('Dausa Junction', 'Dausa'),
('Luni Junction', 'Luni'),
('Merta Road Junction', 'Merta'),
('Degana Junction', 'Degana'),
('Phulera Junction', 'Phulera'),
('Ringas Junction', 'Ringas'),
('Bandikui Junction', 'Bandikui'),
('Hindaun City Junction', 'Hindaun'),
('Bayana Junction', 'Bayana'),
('Abu Road Junction', 'Abu Road'),
('Marwar Junction', 'Marwar'),
('Rani Junction', 'Rani'),
('Falna Junction', 'Falna'),
('Sirohi Road Junction', 'Sirohi'),
('Balotra Junction', 'Balotra'),
('Pokaran Junction', 'Pokaran'),
('Ramdevra Junction', 'Ramdevra'),
('Suratgarh Junction', 'Suratgarh'),
('Anupgarh Junction', 'Anupgarh'),
('Sadulpur Junction', 'Sadulpur'),
('Ratangarh Junction', 'Ratangarh'),
('Nokha Junction', 'Nokha'),
('Makrana Junction', 'Makrana'),
('Kishangarh Junction', 'Kishangarh'),
('Beawar Junction', 'Beawar'),
('Nasirabad Junction', 'Nasirabad'),
('Nimbahera Junction', 'Nimbahera'),
('Rawatbhata Junction', 'Rawatbhata'),
('Baran Junction', 'Baran'),
('Jhalawar Road Junction', 'Jhalawar')
('Himmatnagar Junction', 'Himmatnagar');