INSERT INTO stations (station_name, city) VALUES
('New Delhi Junction', 'New Delhi'),
('Hazrat Nizamuddin', 'New Delhi'),
('Anand Vihar Terminal', 'New Delhi'),
('Mumbai Central', 'Mumbai'),
('Chhatrapati Shivaji Maharaj Terminus', 'Mumbai'),
('Lokmanya Tilak Terminus', 'Mumbai'),
('Chennai Central', 'Chennai'),
('Chennai Egmore', 'Chennai'),
('Howrah Junction', 'Kolkata'),
('Sealdah Junction', 'Kolkata'),
('Bangalore City Junction', 'Bangalore'),
('Yeshwanthpur Junction', 'Bangalore'),
('Hyderabad Deccan', 'Hyderabad'),
('Secunderabad Junction', 'Hyderabad'),
('Ahmedabad Junction', 'Ahmedabad'),
('Surat Junction', 'Surat'),
('Vadodara Junction', 'Vadodara'),
('Pune Junction', 'Pune'),
('Jaipur Junction', 'Jaipur'),
('Jodhpur Junction', 'Jodhpur'),
('Udaipur City', 'Udaipur'),
('Ajmer Junction', 'Ajmer'),
('Kota Junction', 'Kota'),
('Agra Cantt', 'Agra'),
('Mathura Junction', 'Mathura'),
('Lucknow Charbagh', 'Lucknow'),
('Kanpur Central', 'Kanpur'),
('Varanasi Junction', 'Varanasi'),
('Patna Junction', 'Patna'),
('Gaya Junction', 'Gaya'),
('Bhopal Junction', 'Bhopal'),
('Indore Junction', 'Indore'),
('Nagpur Junction', 'Nagpur'),
('Raipur Junction', 'Raipur'),
('Bhubaneswar Junction', 'Bhubaneswar'),
('Puri Junction', 'Puri'),
('Visakhapatnam Junction', 'Visakhapatnam'),
('Vijayawada Junction', 'Vijayawada'),
('Coimbatore Junction', 'Coimbatore'),
('Madurai Junction', 'Madurai'),
('Thiruvananthapuram Central', 'Thiruvananthapuram'),
('Ernakulam Junction', 'Kochi'),
('Kozhikode Junction', 'Kozhikode'),
('Mangaluru Central', 'Mangaluru'),
('Guwahati Junction', 'Guwahati'),
('Dibrugarh Junction', 'Dibrugarh'),
('Jammu Tawi', 'Jammu'),
('Amritsar Junction', 'Amritsar'),
('Ludhiana Junction', 'Ludhiana'),
('Chandigarh Junction', 'Chandigarh'),
('Dehradun Junction', 'Dehradun'),
('Haridwar Junction', 'Haridwar'),
('Allahabad Junction', 'Prayagraj'),
('Jabalpur Junction', 'Jabalpur'),
('Ujjain Junction', 'Ujjain');