INSERT INTO stations (station_name, city) VALUES
('New Delhi Junction', 'New Delhi'),
('Hazrat Nizamuddin', 'New Delhi'),
('Anand Vihar Terminal', 'New Delhi'),
('Mumbai Central', 'Mumbai'),
('Chhatrapati Shivaji Maharaj Terminus', 'Mumbai'),
('Lokmanya Tilak Terminus', 'Mumbai'),
('Chennai Central', 'Chennai'),
('Chennai Egmore', 'Chennai'),
('Howrah Junction', 'Kolkata'),
('Sealdah Junction', 'Kolkata'),
('Bangalore City Junction', 'Bangalore'),
('Yeshwanthpur Junction', 'Bangalore'),
('Hyderabad Deccan', 'Hyderabad'),
('Secunderabad Junction', 'Hyderabad'),
('Ahmedabad Junction', 'Ahmedabad'),
('Surat Junction', 'Surat'),
('Vadodara Junction', 'Vadodara'),
('Pune Junction', 'Pune'),
('Jaipur Junction', 'Jaipur'),
('Jodhpur Junction', 'Jodhpur'),
('Udaipur City', 'Udaipur'),
('Ajmer Junction', 'Ajmer'),
('Kota Junction', 'Kota'),
('Agra Cantt', 'Agra'),
('Mathura Junction', 'Mathura'),
('Lucknow Charbagh', 'Lucknow'),
('Kanpur Central', 'Kanpur'),
('Varanasi Junction', 'Varanasi'),
('Patna Junction', 'Patna'),
('Gaya Junction', 'Gaya'),
('Bhopal Junction', 'Bhopal'),
('Indore Junction', 'Indore'),
('Nagpur Junction', 'Nagpur'),
('Raipur Junction', 'Raipur'),
('Bhubaneswar Junction', 'Bhubaneswar'),
('Puri Junction', 'Puri'),
('Visakhapatnam Junction', 'Visakhapatnam'),
('Vijayawada Junction', 'Vijayawada'),
('Coimbatore Junction', 'Coimbatore'),
('Madurai Junction', 'Madurai'),
('Thiruvananthapuram Central', 'Thiruvananthapuram'),
('Ernakulam Junction', 'Kochi'),
('Kozhikode Junction', 'Kozhikode'),
('Mangaluru Central', 'Mangaluru'),
('Guwahati Junction', 'Guwahati'),
('Dibrugarh Junction', 'Dibrugarh'),
('Jammu Tawi', 'Jammu'),
('Amritsar Junction', 'Amritsar'),
('Ludhiana Junction', 'Ludhiana'),
('Chandigarh Junction', 'Chandigarh'),
('Dehradun Junction', 'Dehradun'),
('Haridwar Junction', 'Haridwar'),
('Allahabad Junction', 'Prayagraj'),
('Jabalpur Junction', 'Jabalpur'),

-- ================================================================
-- RAJASTHAN STATIONS
-- Already in DB (skip these):
-- Jaipur Junction, Jodhpur Junction, Udaipur City,
-- Ajmer Junction, Kota Junction

-- Additional Rajasthan Stations
-- ================================================================
('Ujjain Junction', 'Ujjain'),
('Bikaner Junction', 'Bikaner'),
('Alwar Junction', 'Alwar'),
('Bharatpur Junction', 'Bharatpur'),
('Sawai Madhopur Junction', 'Sawai Madhopur'),
('Gangapur City Junction', 'Gangapur City'),
('Sikar Junction', 'Sikar'),
('Churu Junction', 'Churu'),
('Sri Ganganagar Junction', 'Sri Ganganagar'),
('Hanumangarh Junction', 'Hanumangarh'),
('Sujangarh Junction', 'Sujangarh'),
('Nagaur Junction', 'Nagaur'),
('Pali Marwar Junction', 'Pali'),
('Barmer Junction', 'Barmer'),
('Jaisalmer Junction', 'Jaisalmer'),
('Bhilwara Junction', 'Bhilwara'),
('Chittorgarh Junction', 'Chittorgarh'),
('Dungarpur Road', 'Dungarpur'),
('Banswara Road', 'Banswara'),
('Bundi Junction', 'Bundi'),
('Tonk Junction', 'Tonk'),
('Dausa Junction', 'Dausa'),
('Luni Junction', 'Luni'),
('Merta Road Junction', 'Merta'),
('Degana Junction', 'Degana'),
('Phulera Junction', 'Phulera'),
('Ringas Junction', 'Ringas'),
('Bandikui Junction', 'Bandikui'),
('Hindaun City Junction', 'Hindaun'),
('Bayana Junction', 'Bayana'),
('Abu Road Junction', 'Abu Road'),
('Marwar Junction', 'Marwar'),
('Rani Junction', 'Rani'),
('Falna Junction', 'Falna'),
('Sirohi Road Junction', 'Sirohi'),
('Balotra Junction', 'Balotra'),
('Pokaran Junction', 'Pokaran'),
('Ramdevra Junction', 'Ramdevra'),
('Suratgarh Junction', 'Suratgarh'),
('Anupgarh Junction', 'Anupgarh'),
('Sadulpur Junction', 'Sadulpur'),
('Ratangarh Junction', 'Ratangarh'),
('Nokha Junction', 'Nokha'),
('Makrana Junction', 'Makrana'),
('Kishangarh Junction', 'Kishangarh'),
('Beawar Junction', 'Beawar'),
('Nasirabad Junction', 'Nasirabad'),
('Nimbahera Junction', 'Nimbahera'),
('Rawatbhata Junction', 'Rawatbhata'),
('Baran Junction', 'Baran'),
('Jhalawar Road Junction', 'Jhalawar'),
('Himmatnagar Junction', 'Himmatnagar');